services:
  - type: web
    name: cafepoint-monolith
    runtime: node
    plan: free
    region: frankfurt
    buildCommand: "bash build_render.sh"
    startCommand: "cd backend && npm start"
    envVars:
      - key: NODE_ENV
        value: production
      - key: JWT_SECRET
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: cafepoint-db
          property: connectionString

databases:
  - name: cafepoint-db
    plan: free
    region: frankfurt
    databaseName: cafepoint
    user: admin
